export const defaultCountry = {
  code: 'AR',
  dialCode: '+54',
  flag: '🇦🇷',
  name: 'Argentina',
};

export const countriesList = [
  {
    code: 'AF',
    dialCode: '+93',
    flag: '🇦🇫',
    name: 'Afganistán',
    phoneLength: 9,
  },
  {
    code: 'AL',
    dialCode: '+355',
    flag: '🇦🇱',
    name: 'Albania',
    phoneLength: 9,
  },
  {
    code: 'DE',
    dialCode: '+49',
    flag: '🇩🇪',
    name: 'Alemania',
    phoneLength: 10,
  },
  {
    code: 'AD',
    dialCode: '+376',
    flag: '🇦🇩',
    name: 'Andorra',
    phoneLength: 6,
  },
  {
    code: 'AO',
    dialCode: '+244',
    flag: '🇦🇴',
    name: 'Angola',
    phoneLength: 9,
  },
  {
    code: 'AG',
    dialCode: '+1268',
    flag: '🇦🇬',
    name: 'Antigua y Barbuda',
    phoneLength: 10,
  },
  {
    code: 'SA',
    dialCode: '+966',
    flag: '🇸🇦',
    name: 'Arabia Saudita',
    phoneLength: 9,
  },
  {
    code: 'DZ',
    dialCode: '+213',
    flag: '🇩🇿',
    name: 'Argelia',
    phoneLength: 9,
  },
  {
    code: 'AR',
    dialCode: '+54',
    flag: '🇦🇷',
    latinAmerica: true,
    name: 'Argentina',
    phoneLength: 8,
  },
  {
    code: 'AM',
    dialCode: '+374',
    flag: '🇦🇲',
    name: 'Armenia',
    phoneLength: 6,
  },
  {
    code: 'AU',
    dialCode: '+61',
    flag: '🇦🇺',
    name: 'Australia',
    phoneLength: 9,
  },
  {
    code: 'AT',
    dialCode: '+43',
    flag: '🇦🇹',
    name: 'Austria',
    phoneLength: 9,
  },
  {
    code: 'AZ',
    dialCode: '+994',
    flag: '🇦🇿',
    name: 'Azerbaiyán',
    phoneLength: 9,
  },
  {
    code: 'BS',
    dialCode: '+1242',
    flag: '🇧🇸',
    name: 'Bahamas',
    phoneLength: 10,
  },
  {
    code: 'BD',
    dialCode: '+880',
    flag: '🇧🇩',
    name: 'Bangladés',
    phoneLength: 10,
  },
  {
    code: 'BB',
    dialCode: '+1246',
    flag: '🇧🇧',
    name: 'Barbados',
    phoneLength: 10,
  },
  {
    code: 'BH',
    dialCode: '+973',
    flag: '🇧🇭',
    name: 'Baréin',
    phoneLength: 8,
  },
  {
    code: 'BE',
    dialCode: '+32',
    flag: '🇧🇪',
    name: 'Bélgica',
    phoneLength: 8,
  },
  {
    code: 'BZ',
    dialCode: '+501',
    flag: '🇧🇿',
    name: 'Belice',
    phoneLength: 7,
  },
  {
    code: 'BJ',
    dialCode: '+229',
    flag: '🇧🇯',
    name: 'Benín',
    phoneLength: 8,
  },
  {
    code: 'BY',
    dialCode: '+375',
    flag: '🇧🇾',
    name: 'Bielorrusia',
    phoneLength: 9,
  },
  {
    code: 'MM',
    dialCode: '+95',
    flag: '🇲🇲',
    name: 'Birmania',
    phoneLength: 10,
  },
  {
    code: 'BO',
    dialCode: '+591',
    flag: '🇧🇴',
    latinAmerica: true,
    name: 'Bolivia',
    phoneLength: 9,
  },
  {
    code: 'BA',
    dialCode: '+387',
    flag: '🇧🇦',
    name: 'Bosnia y Herzegovina',
    phoneLength: 8,
  },
  {
    code: 'BW',
    dialCode: '+267',
    flag: '🇧🇼',
    name: 'Botsuana',
    phoneLength: 7,
  },
  {
    code: 'BR',
    dialCode: '+55',
    flag: '🇧🇷',
    latinAmerica: true,
    name: 'Brasil',
    phoneLength: 11,
  },
  {
    code: 'BN',
    dialCode: '+673',
    flag: '🇧🇳',
    name: 'Brunéi',
    phoneLength: 7,
  },
  {
    code: 'BG',
    dialCode: '+359',
    flag: '🇧🇬',
    name: 'Bulgaria',
    phoneLength: 9,
  },
  {
    code: 'BF',
    dialCode: '+226',
    flag: '🇧🇫',
    name: 'Burkina Faso',
    phoneLength: 8,
  },
  {
    code: 'BI',
    dialCode: '+257',
    flag: '🇧🇮',
    name: 'Burundi',
    phoneLength: 8,
  },
  {
    code: 'BT',
    dialCode: '+975',
    flag: '🇧🇹',
    name: 'Bután',
    phoneLength: 7,
  },
  {
    code: 'CV',
    dialCode: '+238',
    flag: '🇨🇻',
    name: 'Cabo Verde',
    phoneLength: 7,
  },
  {
    code: 'KH',
    dialCode: '+855',
    flag: '🇰🇭',
    name: 'Camboya',
    phoneLength: 9,
  },
  {
    code: 'CM',
    dialCode: '+237',
    flag: '🇨🇲',
    name: 'Camerún',
    phoneLength: 9,
  },
  {
    code: 'CA',
    dialCode: '+1',
    flag: '🇨🇦',
    name: 'Canadá',
    phoneLength: 10,
  },
  {
    code: 'QA',
    dialCode: '+974',
    flag: '🇶🇦',
    name: 'Catar',
    phoneLength: 8,
  },
  {
    code: 'TD',
    dialCode: '+235',
    flag: '🇹🇩',
    name: 'Chad',
    phoneLength: 6,
  },
  {
    code: 'CL',
    dialCode: '+56',
    flag: '🇨🇱',
    latinAmerica: true,
    name: 'Chile',
    phoneLength: 9,
  },
  {
    code: 'CN',
    dialCode: '+86',
    flag: '🇨🇳',
    name: 'China',
    phoneLength: 11,
  },
  {
    code: 'CY',
    dialCode: '+357',
    flag: '🇨🇾',
    name: 'Chipre',
    phoneLength: 8,
  },
  {
    code: 'CO',
    dialCode: '+57',
    flag: '🇨🇴',
    latinAmerica: true,
    name: 'Colombia',
    phoneLength: 10,
  },
  {
    code: 'KM',
    dialCode: '+269',
    flag: '🇰🇲',
    name: 'Comoras',
    phoneLength: 7,
  },
  {
    code: 'CG',
    dialCode: '+242',
    flag: '🇨🇬',
    name: 'Congo',
    phoneLength: 9,
  },
  {
    code: 'KP',
    dialCode: '+850',
    flag: '🇰🇵',
    name: 'Corea del Norte',
    phoneLength: 13,
  },
  {
    code: 'KR',
    dialCode: '+82',
    flag: '🇰🇷',
    name: 'Corea del Sur',
    phoneLength: 8,
  },
  {
    code: 'CI',
    dialCode: '+225',
    flag: '🇨🇮',
    name: 'Costa de Marfil',
    phoneLength: 8,
  },
  {
    code: 'CR',
    dialCode: '+506',
    flag: '🇨🇷',
    latinAmerica: true,
    name: 'Costa Rica',
    phoneLength: 8,
  },
  {
    code: 'HR',
    dialCode: '+385',
    flag: '🇭🇷',
    name: 'Croacia',
    phoneLength: 9,
  },
  {
    code: 'CU',
    dialCode: '+53',
    flag: '🇨🇺',
    latinAmerica: true,
    name: 'Cuba',
    phoneLength: 8,
  },
  {
    code: 'DK',
    dialCode: '+45',
    flag: '🇩🇰',
    name: 'Dinamarca',
    phoneLength: 8,
  },
  {
    code: 'DM',
    dialCode: '+1767',
    flag: '🇩🇲',
    name: 'Dominica',
    phoneLength: 10,
  },
  {
    code: 'EC',
    dialCode: '+593',
    flag: '🇪🇨',
    latinAmerica: true,
    name: 'Ecuador',
    phoneLength: 9,
  },
  {
    code: 'EG',
    dialCode: '+20',
    flag: '🇪🇬',
    name: 'Egipto',
    phoneLength: 10,
  },
  {
    code: 'SV',
    dialCode: '+503',
    flag: '🇸🇻',
    latinAmerica: true,
    name: 'El Salvador',
    phoneLength: 8,
  },
  {
    code: 'AE',
    dialCode: '+971',
    flag: '🇦🇪',
    name: 'Emiratos Árabes Unidos',
    phoneLength: 9,
  },
  {
    code: 'ER',
    dialCode: '+291',
    flag: '🇪🇷',
    name: 'Eritrea',
    phoneLength: 7,
  },
  {
    code: 'SK',
    dialCode: '+421',
    flag: '🇸🇰',
    name: 'Eslovaquia',
    phoneLength: 9,
  },
  {
    code: 'SI',
    dialCode: '+386',
    flag: '🇸🇮',
    name: 'Eslovenia',
    phoneLength: 9,
  },
  {
    code: 'ES',
    dialCode: '+34',
    flag: '🇪🇸',
    name: 'España',
    phoneLength: 9,
  },
  {
    code: 'US',
    dialCode: '+1',
    flag: '🇺🇸',
    name: 'Estados Unidos',
    phoneLength: 10,
  },
  {
    code: 'EE',
    dialCode: '+372',
    flag: '🇪🇪',
    name: 'Estonia',
    phoneLength: 8,
  },
  {
    code: 'ET',
    dialCode: '+251',
    flag: '🇪🇹',
    name: 'Etiopía',
    phoneLength: 9,
  },
  {
    code: 'PH',
    dialCode: '+63',
    flag: '🇵🇭',
    name: 'Filipinas',
    phoneLength: 10,
  },
  {
    code: 'FI',
    dialCode: '+358',
    flag: '🇫🇮',
    name: 'Finlandia',
    phoneLength: 11,
  },
  {
    code: 'FJ',
    dialCode: '+679',
    flag: '🇫🇯',
    name: 'Fiyi',
    phoneLength: 7,
  },
  {
    code: 'FR',
    dialCode: '+33',
    flag: '🇫🇷',
    name: 'Francia',
    phoneLength: 9,
  },
  {
    code: 'GA',
    dialCode: '+241',
    flag: '🇬🇦',
    name: 'Gabón',
    phoneLength: 7,
  },
  {
    code: 'GM',
    dialCode: '+220',
    flag: '🇬🇲',
    name: 'Gambia',
    phoneLength: 7,
  },
  {
    code: 'GE',
    dialCode: '+995',
    flag: '🇬🇪',
    name: 'Georgia',
    phoneLength: 9,
  },
  {
    code: 'GH',
    dialCode: '+233',
    flag: '🇬🇭',
    name: 'Ghana',
    phoneLength: 9,
  },
  {
    code: 'GD',
    dialCode: '+1473',
    flag: '🇬🇩',
    name: 'Granada',
    phoneLength: 10,
  },
  {
    code: 'GR',
    dialCode: '+30',
    flag: '🇬🇷',
    name: 'Grecia',
    phoneLength: 10,
  },
  {
    code: 'GT',
    dialCode: '+502',
    flag: '🇬🇹',
    latinAmerica: true,
    name: 'Guatemala',
    phoneLength: 8,
  },
  {
    code: 'GN',
    dialCode: '+224',
    flag: '🇬🇳',
    name: 'Guinea',
    phoneLength: 9,
  },
  {
    code: 'GW',
    dialCode: '+245',
    flag: '🇬🇼',
    name: 'Guinea-Bisáu',
    phoneLength: 9,
  },
  {
    code: 'GQ',
    dialCode: '+240',
    flag: '🇬🇶',
    name: 'Guinea Ecuatorial',
    phoneLength: 9,
  },
  {
    code: 'GY',
    dialCode: '+592',
    flag: '🇬🇾',
    name: 'Guyana',
    phoneLength: 7,
  },
  {
    code: 'HT',
    dialCode: '+509',
    flag: '🇭🇹',
    latinAmerica: true,
    name: 'Haití',
    phoneLength: 8,
  },
  {
    code: 'HN',
    dialCode: '+504',
    flag: '🇭🇳',
    latinAmerica: true,
    name: 'Honduras',
    phoneLength: 8,
  },
  {
    code: 'HU',
    dialCode: '+36',
    flag: '🇭🇺',
    name: 'Hungría',
    phoneLength: 9,
  },
  {
    code: 'IN',
    dialCode: '+91',
    flag: '🇮🇳',
    name: 'India',
    phoneLength: 10,
  },
  {
    code: 'ID',
    dialCode: '+62',
    flag: '🇮🇩',
    name: 'Indonesia',
    phoneLength: 11,
  },
  {
    code: 'IQ',
    dialCode: '+964',
    flag: '🇮🇶',
    name: 'Irak',
    phoneLength: 10,
  },
  {
    code: 'IR',
    dialCode: '+98',
    flag: '🇮🇷',
    name: 'Irán',
    phoneLength: 11,
  },
  {
    code: 'IE',
    dialCode: '+353',
    flag: '🇮🇪',
    name: 'Irlanda',
    phoneLength: 9,
  },
  {
    code: 'IS',
    dialCode: '+354',
    flag: '🇮🇸',
    name: 'Islandia',
    phoneLength: 7,
  },
  {
    code: 'MH',
    dialCode: '+692',
    flag: '🇲🇭',
    name: 'Islas Marshall',
    phoneLength: 7,
  },
  {
    code: 'SB',
    dialCode: '+677',
    flag: '🇸🇧',
    name: 'Islas Salomón',
    phoneLength: 7,
  },
  {
    code: 'IL',
    dialCode: '+972',
    flag: '🇮🇱',
    name: 'Israel',
    phoneLength: 9,
  },
  {
    code: 'IT',
    dialCode: '+39',
    flag: '🇮🇹',
    name: 'Italia',
    phoneLength: 10,
  },
  {
    code: 'JM',
    dialCode: '+1876',
    flag: '🇯🇲',
    name: 'Jamaica',
    phoneLength: 10,
  },
  {
    code: 'JP',
    dialCode: '+81',
    flag: '🇯🇵',
    name: 'Japón',
    phoneLength: 0,
  },
  {
    code: 'JO',
    dialCode: '+962',
    flag: '🇯🇴',
    name: 'Jordania',
    phoneLength: 9,
  },
  {
    code: 'KZ',
    dialCode: '+7',
    flag: '🇰🇿',
    name: 'Kazajistán',
    phoneLength: 10,
  },
  {
    code: 'KE',
    dialCode: '+254',
    flag: '🇰🇪',
    name: 'Kenia',
    phoneLength: 10,
  },
  {
    code: 'KG',
    dialCode: '+996',
    flag: '🇰🇬',
    name: 'Kirguistán',
    phoneLength: 9,
  },
  {
    code: 'KI',
    dialCode: '+686',
    flag: '🇰🇮',
    name: 'Kiribati',
    phoneLength: 8,
  },
  {
    code: 'KW',
    dialCode: '+965',
    flag: '🇰🇼',
    name: 'Kuwait',
    phoneLength: 8,
  },
  {
    code: 'LA',
    dialCode: '+856',
    flag: '🇱🇦',
    name: 'Laos',
    phoneLength: 9,
  },
  {
    code: 'LS',
    dialCode: '+266',
    flag: '🇱🇸',
    name: 'Lesoto',
    phoneLength: 8,
  },
  {
    code: 'LV',
    dialCode: '+371',
    flag: '🇱🇻',
    name: 'Letonia',
    phoneLength: 8,
  },
  {
    code: 'LB',
    dialCode: '+961',
    flag: '🇱🇧',
    name: 'Líbano',
    phoneLength: 8,
  },
  {
    code: 'LR',
    dialCode: '+231',
    flag: '🇱🇷',
    name: 'Liberia',
    phoneLength: 9,
  },
  {
    code: 'LY',
    dialCode: '+218',
    flag: '🇱🇾',
    name: 'Libia',
    phoneLength: 10,
  },
  {
    code: 'LI',
    dialCode: '+423',
    flag: '🇱🇮',
    name: 'Liechtenstein',
    phoneLength: 7,
  },
  {
    code: 'LT',
    dialCode: '+370',
    flag: '🇱🇹',
    name: 'Lituania',
    phoneLength: 8,
  },
  {
    code: 'LU',
    dialCode: '+352',
    flag: '🇱🇺',
    name: 'Luxemburgo',
    phoneLength: 9,
  },
  {
    code: 'MG',
    dialCode: '+261',
    flag: '🇲🇬',
    name: 'Madagascar',
    phoneLength: 7,
  },
  {
    code: 'MY',
    dialCode: '+60',
    flag: '🇲🇾',
    name: 'Malasia',
    phoneLength: 7,
  },
  {
    code: 'MW',
    dialCode: '+265',
    flag: '🇲🇼',
    name: 'Malaui',
    phoneLength: 9,
  },
  {
    code: 'MV',
    dialCode: '+960',
    flag: '🇲🇻',
    name: 'Maldivas',
    phoneLength: 7,
  },
  {
    code: 'ML',
    dialCode: '+223',
    flag: '🇲🇱',
    name: 'Malí',
    phoneLength: 8,
  },
  {
    code: 'MT',
    dialCode: '+356',
    flag: '🇲🇹',
    name: 'Malta',
    phoneLength: 8,
  },
  {
    code: 'MA',
    dialCode: '+212',
    flag: '🇲🇦',
    name: 'Marruecos',
    phoneLength: 9,
  },
  {
    code: 'MU',
    dialCode: '+230',
    flag: '🇲🇺',
    name: 'Mauricio',
    phoneLength: 8,
  },
  {
    code: 'MR',
    dialCode: '+222',
    flag: '🇲🇷',
    name: 'Mauritania',
    phoneLength: 8,
  },
  {
    code: 'MX',
    dialCode: '+52',
    flag: '🇲🇽',
    latinAmerica: true,
    name: 'México',
    phoneLength: 10,
  },
  {
    code: 'FM',
    dialCode: '+691',
    flag: '🇫🇲',
    name: 'Micronesia',
    phoneLength: 7,
  },
  {
    code: 'MD',
    dialCode: '+373',
    flag: '🇲🇩',
    name: 'Moldavia',
    phoneLength: 8,
  },
  {
    code: 'MC',
    dialCode: '+377',
    flag: '🇲🇨',
    name: 'Mónaco',
    phoneLength: 8,
  },
  {
    code: 'MN',
    dialCode: '+976',
    flag: '🇲🇳',
    name: 'Mongolia',
    phoneLength: 8,
  },
  {
    code: 'ME',
    dialCode: '+382',
    flag: '🇲🇪',
    name: 'Montenegro',
    phoneLength: 8,
  },
  {
    code: 'MZ',
    dialCode: '+258',
    flag: '🇲🇿',
    name: 'Mozambique',
    phoneLength: 12,
  },
  {
    code: 'NA',
    dialCode: '+264',
    flag: '🇳🇦',
    name: 'Namibia',
    phoneLength: 7,
  },
  {
    code: 'NR',
    dialCode: '+674',
    flag: '🇳🇷',
    name: 'Nauru',
    phoneLength: 7,
  },
  {
    code: 'NP',
    dialCode: '+977',
    flag: '🇳🇵',
    name: 'Nepal',
    phoneLength: 10,
  },
  {
    code: 'NI',
    dialCode: '+505',
    flag: '🇳🇮',
    latinAmerica: true,
    name: 'Nicaragua',
    phoneLength: 8,
  },
  {
    code: 'NE',
    dialCode: '+227',
    flag: '🇳🇪',
    name: 'Níger',
    phoneLength: 8,
  },
  {
    code: 'NG',
    dialCode: '+234',
    flag: '🇳🇬',
    name: 'Nigeria',
    phoneLength: 8,
  },
  {
    code: 'NO',
    dialCode: '+47',
    flag: '🇳🇴',
    name: 'Noruega',
    phoneLength: 8,
  },
  {
    code: 'NZ',
    dialCode: '+64',
    flag: '🇳🇿',
    name: 'Nueva Zelanda',
    phoneLength: 9,
  },
  {
    code: 'OM',
    dialCode: '+968',
    flag: '🇴🇲',
    name: 'Omán',
    phoneLength: 8,
  },
  {
    code: 'NL',
    dialCode: '+31',
    flag: '🇳🇱',
    name: 'Países Bajos',
    phoneLength: 9,
  },
  {
    code: 'PK',
    dialCode: '+92',
    flag: '🇵🇰',
    name: 'Pakistán',
    phoneLength: 10,
  },
  {
    code: 'PW',
    dialCode: '+680',
    flag: '🇵🇼',
    name: 'Palaos',
    phoneLength: 7,
  },
  {
    code: 'PA',
    dialCode: '+507',
    flag: '🇵🇦',
    latinAmerica: true,
    name: 'Panamá',
    phoneLength: 8,
  },
  {
    code: 'PG',
    dialCode: '+675',
    flag: '🇵🇬',
    name: 'Papúa Nueva Guinea',
    phoneLength: 8,
  },
  {
    code: 'PY',
    dialCode: '+595',
    flag: '🇵🇾',
    latinAmerica: true,
    name: 'Paraguay',
    phoneLength: 9,
  },
  {
    code: 'PE',
    dialCode: '+51',
    flag: '🇵🇪',
    latinAmerica: true,
    name: 'Perú',
    phoneLength: 9,
  },
  {
    code: 'PL',
    dialCode: '+48',
    flag: '🇵🇱',
    name: 'Polonia',
    phoneLength: 9,
  },
  {
    code: 'PT',
    dialCode: '+351',
    flag: '🇵🇹',
    name: 'Portugal',
    phoneLength: 9,
  },
  {
    code: 'GB',
    dialCode: '+44',
    flag: '🇬🇧',
    name: 'Reino Unido',
    phoneLength: 10,
  },
  {
    code: 'CF',
    dialCode: '+236',
    flag: '🇨🇫',
    name: 'República Centroafricana',
    phoneLength: 8,
  },
  {
    code: 'CZ',
    dialCode: '+420',
    flag: '🇨🇿',
    name: 'República Checa',
    phoneLength: 9,
  },
  {
    code: 'CD',
    dialCode: '+243',
    flag: '🇨🇩',
    name: 'República del Congo',
    phoneLength: 7,
  },
  {
    code: 'DO',
    dialCode: '+1809',
    flag: '🇩🇴',
    latinAmerica: true,
    name: 'República Dominicana',
    phoneLength: 10,
  },
  {
    code: 'RW',
    dialCode: '+250',
    flag: '🇷🇼',
    name: 'Ruanda',
    phoneLength: 9,
  },
  {
    code: 'RO',
    dialCode: '+40',
    flag: '🇷🇴',
    name: 'Rumania',
    phoneLength: 10,
  },
  {
    code: 'RU',
    dialCode: '+7',
    flag: '🇷🇺',
    name: 'Rusia',
    phoneLength: 10,
  },
  {
    code: 'WS',
    dialCode: '+685',
    flag: '🇼🇸',
    name: 'Samoa',
    phoneLength: 7,
  },
  {
    code: 'KN',
    dialCode: '+1869',
    flag: '🇰🇳',
    name: 'San Cristóbal y Nieves',
    phoneLength: 10,
  },
  {
    code: 'SM',
    dialCode: '+378',
    flag: '🇸🇲',
    name: 'San Marino',
    phoneLength: 10,
  },
  {
    code: 'LC',
    dialCode: '+1758',
    flag: '🇱🇨',
    name: 'Santa Lucía',
    phoneLength: 7,
  },
  {
    code: 'ST',
    dialCode: '+239',
    flag: '🇸🇹',
    name: 'Santo Tomé y Príncipe',
    phoneLength: 7,
  },
  {
    code: 'VC',
    dialCode: '+1784',
    flag: '🇻🇨',
    name: 'San Vicente y las Granadinas',
    phoneLength: 7,
  },
  {
    code: 'SN',
    dialCode: '+221',
    flag: '🇸🇳',
    name: 'Senegal',
    phoneLength: 9,
  },
  {
    code: 'RS',
    dialCode: '+381',
    flag: '🇷🇸',
    name: 'Serbia',
    phoneLength: 9,
  },
  {
    code: 'SC',
    dialCode: '+248',
    flag: '🇸🇨',
    name: 'Seychelles',
    phoneLength: 7,
  },
  {
    code: 'SL',
    dialCode: '+232',
    flag: '🇸🇱',
    name: 'Sierra Leona',
    phoneLength: 8,
  },
  {
    code: 'SG',
    dialCode: '+65',
    flag: '🇸🇬',
    name: 'Singapur',
    phoneLength: 8,
  },
  {
    code: 'SY',
    dialCode: '+963',
    flag: '🇸🇾',
    name: 'Siria',
    phoneLength: 7,
  },
  {
    code: 'SO',
    dialCode: '+252',
    flag: '🇸🇴',
    name: 'Somalia',
    phoneLength: 9,
  },
  {
    code: 'LK',
    dialCode: '+94',
    flag: '🇱🇰',
    name: 'Sri Lanka',
    phoneLength: 7,
  },
  {
    code: 'ZA',
    dialCode: '+27',
    flag: '🇿🇦',
    name: 'Sudáfrica',
    phoneLength: 9,
  },
  {
    code: 'SD',
    dialCode: '+249',
    flag: '🇸🇩',
    name: 'Sudán',
    phoneLength: 7,
  },
  {
    code: 'SS',
    dialCode: '+211',
    flag: '🇸🇸',
    name: 'Sudán del Sur',
    phoneLength: 7,
  },
  {
    code: 'SE',
    dialCode: '+46',
    flag: '🇸🇪',
    name: 'Suecia',
    phoneLength: 7,
  },
  {
    code: 'CH',
    dialCode: '+41',
    flag: '🇨🇭',
    name: 'Suiza',
    phoneLength: 9,
  },
  {
    code: 'SR',
    dialCode: '+597',
    flag: '🇸🇷',
    name: 'Surinam',
    phoneLength: 7,
  },
  {
    code: 'TH',
    dialCode: '+66',
    flag: '🇹🇭',
    name: 'Tailandia',
    phoneLength: 9,
  },
  {
    code: 'TZ',
    dialCode: '+255',
    flag: '🇹🇿',
    name: 'Tanzania',
    phoneLength: 7,
  },
  {
    code: 'TJ',
    dialCode: '+992',
    flag: '🇹🇯',
    name: 'Tayikistán',
    phoneLength: 9,
  },
  {
    code: 'TL',
    dialCode: '+670',
    flag: '🇹🇱',
    name: 'Timor Oriental',
    phoneLength: 7,
  },
  {
    code: 'TG',
    dialCode: '+228',
    flag: '🇹🇬',
    name: 'Togo',
    phoneLength: 8,
  },
  {
    code: 'TO',
    dialCode: '+676',
    flag: '🇹🇴',
    name: 'Tonga',
    phoneLength: 5,
  },
  {
    code: 'TT',
    dialCode: '+1868',
    flag: '🇹🇹',
    name: 'Trinidad y Tobago',
    phoneLength: 7,
  },
  {
    code: 'TN',
    dialCode: '+216',
    flag: '🇹🇳',
    name: 'Túnez',
    phoneLength: 8,
  },
  {
    code: 'TM',
    dialCode: '+993',
    flag: '🇹🇲',
    name: 'Turkmenistán',
    phoneLength: 8,
  },
  {
    code: 'TR',
    dialCode: '+90',
    flag: '🇹🇷',
    name: 'Turquía',
    phoneLength: 11,
  },
  {
    code: 'TV',
    dialCode: '+688',
    flag: '🇹🇻',
    name: 'Tuvalu',
    phoneLength: 5,
  },
  {
    code: 'UA',
    dialCode: '+380',
    flag: '🇺🇦',
    name: 'Ucrania',
    phoneLength: 9,
  },
  {
    code: 'UG',
    dialCode: '+256',
    flag: '🇺🇬',
    name: 'Uganda',
    phoneLength: 7,
  },
  {
    code: 'UY',
    dialCode: '+598',
    flag: '🇺🇾',
    latinAmerica: true,
    name: 'Uruguay',
    phoneLength: 8,
  },
  {
    code: 'UZ',
    dialCode: '+998',
    flag: '🇺🇿',
    name: 'Uzbekistán',
    phoneLength: 9,
  },
  {
    code: 'VU',
    dialCode: '+678',
    flag: '🇻🇺',
    name: 'Vanuatu',
    phoneLength: 5,
  },
  {
    code: 'VE',
    dialCode: '+58',
    flag: '🇻🇪',
    latinAmerica: true,
    name: 'Venezuela',
    phoneLength: 7,
  },
  {
    code: 'VN',
    dialCode: '+84',
    flag: '🇻🇳',
    name: 'Vietnam',
    phoneLength: 9,
  },
  {
    code: 'YE',
    dialCode: '+967',
    flag: '🇾🇪',
    name: 'Yemen',
    phoneLength: 9,
  },
  {
    code: 'DJ',
    dialCode: '+253',
    flag: '🇩🇯',
    name: 'Yibuti',
    phoneLength: 10,
  },
  {
    code: 'ZM',
    dialCode: '+260',
    flag: '🇿🇲',
    name: 'Zambia',
    phoneLength: 9,
  },
  {
    code: 'ZW',
    dialCode: '+263',
    flag: '🇿🇼',
    name: 'Zimbabue',
    phoneLength: 9,
  },
];
